name: midterm_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.3.1
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_map: ^8.3.1
  flutter_riverpod: ^2.6.1
  geolocator: ^14.0.3
  image_picker: ^1.2.3
  intl: ^0.20.0
  latlong2: ^0.10.1
  path: ^1.9.0
  path_provider: ^2.1.6
  sqflite: ^2.4.3
  workmanager: ^0.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
